spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-oauth?useUnicode=true&characterEncod ing=utf8&characterSetResults=utf8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 5000
  servlet:
    context-path: /authServer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/