spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
        bootstrap: true
  profiles:
    active: native
server:
  port: 7700

